version: "3.1"
services:
  postgres-db:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - ./data:/data
    environment:
      POSTGRES_DB: event_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: postgres -c shared_buffers=512MB -c effective_cache_size=1536MB -c work_mem=2621kB -c maintenance_work_mem=128MB
    shm_size: '1gb'

  datomic-free-transactor:
    image: gordonstratton/datomic-free-transactor:latest
    ports:
      - "4334-4336:4334-4336"
    volumes:
      - ./data:/srv/datomic/data
